site_name: Bharat Anand Notes

theme:
    name: material

    features:
        - navigation.tabs
        - navigation.indexes
        # - toc.integrate
        - header.autohide
    palette:
        - scheme: default
        # primary: blue grey
        # accent: black
        
extra_css:
  - stylesheets/extra.css


plugins:
  - search
  - pheasant
  
nav:
    - Home: index.md
    - Algorithms:
        - Feature Engineering:
            - Feature: 
                - 'algorithms/index.md'
                - 'Understanding Features': 'Technology/SQL/abc.md'
                - 'Local Outlier Factor2': 'about.md'
                - 'Local Outlier Factor3': 'about.md'
        - Feature Elimination:
            - 'Local Outlier Factor': 'about.md'

        - Regression:
            - 'Linear Regression': 'algorithms/regression/reg.md'
        - Classification:
            - 'License': 'about.md'
        - Clustering:
            - 'K-Means': 'about.md'
            - 'Local Outlier Factor': 'algorithms/clustering/local_outlier_detection.md'    
    - Technology:
        - SQL:
            - 'Indexing' : 'Technology/SQL/Indexing.md'
    - Documentation:
        - 'mk-docs' : 'Documentations/mk-docs.md'
        - 'azure blob storage' : 'Documentations/blob-storage.md'
    - Misc:
        - 'Email Notifications' : 'Misc/email_notifications.md'